// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuSxEoMnN7buQRBcNsdHoiVSy_gtcAMag',
    appId: '1:202213348151:android:79bfa95e1668f622c480b2',
    messagingSenderId: '202213348151',
    projectId: 'minh-menh-ai-prod',
    storageBucket: 'minh-menh-ai-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuu1ct0GxTEyL9waF22hPAjwozWwg9Xzo',
    appId: '1:202213348151:ios:dfcd2d5b26a6aa6ec480b2',
    messagingSenderId: '202213348151',
    projectId: 'minh-menh-ai-prod',
    storageBucket: 'minh-menh-ai-prod.firebasestorage.app',
    iosBundleId: 'ai.minhmenh.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuu1ct0GxTEyL9waF22hPAjwozWwg9Xzo',
    appId: '1:202213348151:ios:87e8709246a01a8ac480b2',
    messagingSenderId: '202213348151',
    projectId: 'minh-menh-ai-prod',
    storageBucket: 'minh-menh-ai-prod.firebasestorage.app',
    iosBundleId: 'ai.minhmenh.desktop',
  );
}
