// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/local/objectbox/objectbox_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7214849939856827600),
    name: 'AiConversationEntity',
    lastPropertyId: const obx_int.IdUid(6, 8403951346176235351),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5685252119997259433),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5311124231946785693),
        name: 'conversationId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 5322487590774138348),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8420710654784438094),
        name: 'profileId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 730032932035050699),
        name: 'scope',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7533527270278125534),
        name: 'messagesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8403951346176235351),
        name: 'updatedAtEpochMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3084805939216695113),
    name: 'BirthProfileEntity',
    lastPropertyId: const obx_int.IdUid(13, 6324015001378441196),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7713392161987756648),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2968584291484813986),
        name: 'profileId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 8602170406040551771),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3684174223468429631),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2296421538829007489),
        name: 'gender',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5410984272940670618),
        name: 'calendarType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5626898949475238432),
        name: 'birthDateEpochMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4307332187189527937),
        name: 'birthHourLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3904124819717154219),
        name: 'birthMinute',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1367391078754918604),
        name: 'birthPlace',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8921380749159488049),
        name: 'timezone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4170744330848501019),
        name: 'birthTimeConfidence',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4622382084317741833),
        name: 'mainFocusJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6324015001378441196),
        name: 'isMain',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 3035018864492799),
    name: 'ChartCacheEntity',
    lastPropertyId: const obx_int.IdUid(10, 6605123374854475532),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1680232419540582472),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1038039391353002594),
        name: 'cacheKey',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 3027275653452146475),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3024910800333876217),
        name: 'profileId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2742494022959500720),
        name: 'year',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8240880058288006251),
        name: 'engineVersion',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7185823625621989999),
        name: 'schemaVersion',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6510489921637633127),
        name: 'snapshotHash',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 193429910191602959),
        name: 'snapshotJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7934855025616346974),
        name: 'summaryJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6605123374854475532),
        name: 'updatedAtEpochMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 6696205232324122087),
    name: 'JournalEntryEntity',
    lastPropertyId: const obx_int.IdUid(9, 5252270761342260510),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2142375132986797498),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 511794487210565900),
        name: 'entryId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 2988437174491977857),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 333283266025190860),
        name: 'profileId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3784243889577580406),
        name: 'createdAtLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5995761461825953012),
        name: 'createdAtEpochMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 359324072664511776),
        name: 'mood',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2838297002201591119),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2741103919678459213),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5252270761342260510),
        name: 'sentimentLabel',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 6471313590470322193),
    name: 'PendingSyncOperationEntity',
    lastPropertyId: const obx_int.IdUid(8, 4073092565859604303),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1571105847141356862),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6766323429196878290),
        name: 'operationId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 3965608819768417437),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6459889079103322788),
        name: 'entityType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 588909802796338172),
        name: 'operationType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 128748988929636731),
        name: 'payloadJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7647301707021254511),
        name: 'createdAtEpochMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1689357015768224643),
        name: 'lastAttemptAtEpochMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4073092565859604303),
        name: 'attemptCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 4254405816044940971),
    name: 'UnlockContentEntity',
    lastPropertyId: const obx_int.IdUid(8, 3901249359657998380),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6282392890392517761),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1331804261498512350),
        name: 'unlockKey',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(6, 686466458188735135),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 464837550299820645),
        name: 'profileId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7556630099026887475),
        name: 'contentType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1308405042862530048),
        name: 'contentKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2348055993326926879),
        name: 'unlockMethod',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 590138103095176634),
        name: 'coinSpent',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3901249359657998380),
        name: 'createdAtEpochMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 4870267163242312720),
    name: 'WalletLedgerEntity',
    lastPropertyId: const obx_int.IdUid(7, 6120607296954138296),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5808927394710995300),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1786321438371148775),
        name: 'entryId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(7, 2270396026455495373),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3634398225963179189),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8607497403180614269),
        name: 'amount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4861433256517730561),
        name: 'createdAtLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2739802351716905808),
        name: 'createdAtEpochMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6120607296954138296),
        name: 'source',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 1454402424724474423),
    name: 'WalletSnapshotEntity',
    lastPropertyId: const obx_int.IdUid(6, 5180451066744389878),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 992814226736439474),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8224877422167557759),
        name: 'snapshotKey',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(8, 3901579788368243262),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2379599736239130219),
        name: 'balance',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1813563913611671290),
        name: 'activePlanLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7670273123080668662),
        name: 'historyJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5180451066744389878),
        name: 'updatedAtEpochMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(8, 1454402424724474423),
    lastIndexId: const obx_int.IdUid(8, 3901579788368243262),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AiConversationEntity: obx_int.EntityDefinition<AiConversationEntity>(
      model: _entities[0],
      toOneRelations: (AiConversationEntity object) => [],
      toManyRelations: (AiConversationEntity object) => {},
      getId: (AiConversationEntity object) => object.dbId,
      setId: (AiConversationEntity object, int id) {
        object.dbId = id;
      },
      objectToFB: (AiConversationEntity object, fb.Builder fbb) {
        final conversationIdOffset = fbb.writeString(object.conversationId);
        final profileIdOffset = fbb.writeString(object.profileId);
        final scopeOffset = fbb.writeString(object.scope);
        final messagesJsonOffset = fbb.writeString(object.messagesJson);
        fbb.startTable(7);
        fbb.addInt64(0, object.dbId);
        fbb.addOffset(1, conversationIdOffset);
        fbb.addOffset(2, profileIdOffset);
        fbb.addOffset(3, scopeOffset);
        fbb.addOffset(4, messagesJsonOffset);
        fbb.addInt64(5, object.updatedAtEpochMs);
        fbb.finish(fbb.endTable());
        return object.dbId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dbIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final conversationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final profileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final scopeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final messagesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final updatedAtEpochMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = AiConversationEntity(
          dbId: dbIdParam,
          conversationId: conversationIdParam,
          profileId: profileIdParam,
          scope: scopeParam,
          messagesJson: messagesJsonParam,
          updatedAtEpochMs: updatedAtEpochMsParam,
        );

        return object;
      },
    ),
    BirthProfileEntity: obx_int.EntityDefinition<BirthProfileEntity>(
      model: _entities[1],
      toOneRelations: (BirthProfileEntity object) => [],
      toManyRelations: (BirthProfileEntity object) => {},
      getId: (BirthProfileEntity object) => object.dbId,
      setId: (BirthProfileEntity object, int id) {
        object.dbId = id;
      },
      objectToFB: (BirthProfileEntity object, fb.Builder fbb) {
        final profileIdOffset = fbb.writeString(object.profileId);
        final nameOffset = fbb.writeString(object.name);
        final genderOffset = fbb.writeString(object.gender);
        final calendarTypeOffset = fbb.writeString(object.calendarType);
        final birthHourLabelOffset = fbb.writeString(object.birthHourLabel);
        final birthPlaceOffset = object.birthPlace == null
            ? null
            : fbb.writeString(object.birthPlace!);
        final timezoneOffset = fbb.writeString(object.timezone);
        final birthTimeConfidenceOffset = fbb.writeString(
          object.birthTimeConfidence,
        );
        final mainFocusJsonOffset = fbb.writeString(object.mainFocusJson);
        fbb.startTable(14);
        fbb.addInt64(0, object.dbId);
        fbb.addOffset(1, profileIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, genderOffset);
        fbb.addOffset(4, calendarTypeOffset);
        fbb.addInt64(5, object.birthDateEpochMs);
        fbb.addOffset(6, birthHourLabelOffset);
        fbb.addInt64(7, object.birthMinute);
        fbb.addOffset(8, birthPlaceOffset);
        fbb.addOffset(9, timezoneOffset);
        fbb.addOffset(10, birthTimeConfidenceOffset);
        fbb.addOffset(11, mainFocusJsonOffset);
        fbb.addBool(12, object.isMain);
        fbb.finish(fbb.endTable());
        return object.dbId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dbIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final profileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final genderParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final calendarTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final birthDateEpochMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final birthHourLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final timezoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final birthTimeConfidenceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final mainFocusJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final isMainParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          28,
          false,
        );
        final birthMinuteParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final birthPlaceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = BirthProfileEntity(
          dbId: dbIdParam,
          profileId: profileIdParam,
          name: nameParam,
          gender: genderParam,
          calendarType: calendarTypeParam,
          birthDateEpochMs: birthDateEpochMsParam,
          birthHourLabel: birthHourLabelParam,
          timezone: timezoneParam,
          birthTimeConfidence: birthTimeConfidenceParam,
          mainFocusJson: mainFocusJsonParam,
          isMain: isMainParam,
          birthMinute: birthMinuteParam,
          birthPlace: birthPlaceParam,
        );

        return object;
      },
    ),
    ChartCacheEntity: obx_int.EntityDefinition<ChartCacheEntity>(
      model: _entities[2],
      toOneRelations: (ChartCacheEntity object) => [],
      toManyRelations: (ChartCacheEntity object) => {},
      getId: (ChartCacheEntity object) => object.dbId,
      setId: (ChartCacheEntity object, int id) {
        object.dbId = id;
      },
      objectToFB: (ChartCacheEntity object, fb.Builder fbb) {
        final cacheKeyOffset = fbb.writeString(object.cacheKey);
        final profileIdOffset = fbb.writeString(object.profileId);
        final engineVersionOffset = fbb.writeString(object.engineVersion);
        final schemaVersionOffset = fbb.writeString(object.schemaVersion);
        final snapshotHashOffset = fbb.writeString(object.snapshotHash);
        final snapshotJsonOffset = fbb.writeString(object.snapshotJson);
        final summaryJsonOffset = fbb.writeString(object.summaryJson);
        fbb.startTable(11);
        fbb.addInt64(0, object.dbId);
        fbb.addOffset(1, cacheKeyOffset);
        fbb.addOffset(2, profileIdOffset);
        fbb.addInt64(3, object.year);
        fbb.addOffset(4, engineVersionOffset);
        fbb.addOffset(5, schemaVersionOffset);
        fbb.addOffset(6, snapshotHashOffset);
        fbb.addOffset(7, snapshotJsonOffset);
        fbb.addOffset(8, summaryJsonOffset);
        fbb.addInt64(9, object.updatedAtEpochMs);
        fbb.finish(fbb.endTable());
        return object.dbId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dbIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final cacheKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final profileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final yearParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final engineVersionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final schemaVersionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final snapshotHashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final snapshotJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final summaryJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final updatedAtEpochMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final object = ChartCacheEntity(
          dbId: dbIdParam,
          cacheKey: cacheKeyParam,
          profileId: profileIdParam,
          year: yearParam,
          engineVersion: engineVersionParam,
          schemaVersion: schemaVersionParam,
          snapshotHash: snapshotHashParam,
          snapshotJson: snapshotJsonParam,
          summaryJson: summaryJsonParam,
          updatedAtEpochMs: updatedAtEpochMsParam,
        );

        return object;
      },
    ),
    JournalEntryEntity: obx_int.EntityDefinition<JournalEntryEntity>(
      model: _entities[3],
      toOneRelations: (JournalEntryEntity object) => [],
      toManyRelations: (JournalEntryEntity object) => {},
      getId: (JournalEntryEntity object) => object.dbId,
      setId: (JournalEntryEntity object, int id) {
        object.dbId = id;
      },
      objectToFB: (JournalEntryEntity object, fb.Builder fbb) {
        final entryIdOffset = fbb.writeString(object.entryId);
        final profileIdOffset = fbb.writeString(object.profileId);
        final createdAtLabelOffset = fbb.writeString(object.createdAtLabel);
        final moodOffset = fbb.writeString(object.mood);
        final titleOffset = fbb.writeString(object.title);
        final bodyOffset = fbb.writeString(object.body);
        final sentimentLabelOffset = fbb.writeString(object.sentimentLabel);
        fbb.startTable(10);
        fbb.addInt64(0, object.dbId);
        fbb.addOffset(1, entryIdOffset);
        fbb.addOffset(2, profileIdOffset);
        fbb.addOffset(3, createdAtLabelOffset);
        fbb.addInt64(4, object.createdAtEpochMs);
        fbb.addOffset(5, moodOffset);
        fbb.addOffset(6, titleOffset);
        fbb.addOffset(7, bodyOffset);
        fbb.addOffset(8, sentimentLabelOffset);
        fbb.finish(fbb.endTable());
        return object.dbId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dbIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final entryIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final profileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final createdAtEpochMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final moodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final sentimentLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final object = JournalEntryEntity(
          dbId: dbIdParam,
          entryId: entryIdParam,
          profileId: profileIdParam,
          createdAtLabel: createdAtLabelParam,
          createdAtEpochMs: createdAtEpochMsParam,
          mood: moodParam,
          title: titleParam,
          body: bodyParam,
          sentimentLabel: sentimentLabelParam,
        );

        return object;
      },
    ),
    PendingSyncOperationEntity:
        obx_int.EntityDefinition<PendingSyncOperationEntity>(
          model: _entities[4],
          toOneRelations: (PendingSyncOperationEntity object) => [],
          toManyRelations: (PendingSyncOperationEntity object) => {},
          getId: (PendingSyncOperationEntity object) => object.dbId,
          setId: (PendingSyncOperationEntity object, int id) {
            object.dbId = id;
          },
          objectToFB: (PendingSyncOperationEntity object, fb.Builder fbb) {
            final operationIdOffset = fbb.writeString(object.operationId);
            final entityTypeOffset = fbb.writeString(object.entityType);
            final operationTypeOffset = fbb.writeString(object.operationType);
            final payloadJsonOffset = fbb.writeString(object.payloadJson);
            fbb.startTable(9);
            fbb.addInt64(0, object.dbId);
            fbb.addOffset(1, operationIdOffset);
            fbb.addOffset(2, entityTypeOffset);
            fbb.addOffset(3, operationTypeOffset);
            fbb.addOffset(4, payloadJsonOffset);
            fbb.addInt64(5, object.createdAtEpochMs);
            fbb.addInt64(6, object.lastAttemptAtEpochMs);
            fbb.addInt64(7, object.attemptCount);
            fbb.finish(fbb.endTable());
            return object.dbId;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final dbIdParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final operationIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final entityTypeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final operationTypeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 10, '');
            final payloadJsonParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 12, '');
            final createdAtEpochMsParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              14,
              0,
            );
            final lastAttemptAtEpochMsParam = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 16);
            final attemptCountParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              18,
              0,
            );
            final object = PendingSyncOperationEntity(
              dbId: dbIdParam,
              operationId: operationIdParam,
              entityType: entityTypeParam,
              operationType: operationTypeParam,
              payloadJson: payloadJsonParam,
              createdAtEpochMs: createdAtEpochMsParam,
              lastAttemptAtEpochMs: lastAttemptAtEpochMsParam,
              attemptCount: attemptCountParam,
            );

            return object;
          },
        ),
    UnlockContentEntity: obx_int.EntityDefinition<UnlockContentEntity>(
      model: _entities[5],
      toOneRelations: (UnlockContentEntity object) => [],
      toManyRelations: (UnlockContentEntity object) => {},
      getId: (UnlockContentEntity object) => object.dbId,
      setId: (UnlockContentEntity object, int id) {
        object.dbId = id;
      },
      objectToFB: (UnlockContentEntity object, fb.Builder fbb) {
        final unlockKeyOffset = fbb.writeString(object.unlockKey);
        final profileIdOffset = fbb.writeString(object.profileId);
        final contentTypeOffset = fbb.writeString(object.contentType);
        final contentKeyOffset = fbb.writeString(object.contentKey);
        final unlockMethodOffset = fbb.writeString(object.unlockMethod);
        fbb.startTable(9);
        fbb.addInt64(0, object.dbId);
        fbb.addOffset(1, unlockKeyOffset);
        fbb.addOffset(2, profileIdOffset);
        fbb.addOffset(3, contentTypeOffset);
        fbb.addOffset(4, contentKeyOffset);
        fbb.addOffset(5, unlockMethodOffset);
        fbb.addInt64(6, object.coinSpent);
        fbb.addInt64(7, object.createdAtEpochMs);
        fbb.finish(fbb.endTable());
        return object.dbId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dbIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final unlockKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final profileIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final contentKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final unlockMethodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final coinSpentParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final createdAtEpochMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = UnlockContentEntity(
          dbId: dbIdParam,
          unlockKey: unlockKeyParam,
          profileId: profileIdParam,
          contentType: contentTypeParam,
          contentKey: contentKeyParam,
          unlockMethod: unlockMethodParam,
          coinSpent: coinSpentParam,
          createdAtEpochMs: createdAtEpochMsParam,
        );

        return object;
      },
    ),
    WalletLedgerEntity: obx_int.EntityDefinition<WalletLedgerEntity>(
      model: _entities[6],
      toOneRelations: (WalletLedgerEntity object) => [],
      toManyRelations: (WalletLedgerEntity object) => {},
      getId: (WalletLedgerEntity object) => object.dbId,
      setId: (WalletLedgerEntity object, int id) {
        object.dbId = id;
      },
      objectToFB: (WalletLedgerEntity object, fb.Builder fbb) {
        final entryIdOffset = fbb.writeString(object.entryId);
        final titleOffset = fbb.writeString(object.title);
        final createdAtLabelOffset = fbb.writeString(object.createdAtLabel);
        final sourceOffset = fbb.writeString(object.source);
        fbb.startTable(8);
        fbb.addInt64(0, object.dbId);
        fbb.addOffset(1, entryIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(3, object.amount);
        fbb.addOffset(4, createdAtLabelOffset);
        fbb.addInt64(5, object.createdAtEpochMs);
        fbb.addOffset(6, sourceOffset);
        fbb.finish(fbb.endTable());
        return object.dbId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dbIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final entryIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final amountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final createdAtLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtEpochMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final sourceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final object = WalletLedgerEntity(
          dbId: dbIdParam,
          entryId: entryIdParam,
          title: titleParam,
          amount: amountParam,
          createdAtLabel: createdAtLabelParam,
          createdAtEpochMs: createdAtEpochMsParam,
          source: sourceParam,
        );

        return object;
      },
    ),
    WalletSnapshotEntity: obx_int.EntityDefinition<WalletSnapshotEntity>(
      model: _entities[7],
      toOneRelations: (WalletSnapshotEntity object) => [],
      toManyRelations: (WalletSnapshotEntity object) => {},
      getId: (WalletSnapshotEntity object) => object.dbId,
      setId: (WalletSnapshotEntity object, int id) {
        object.dbId = id;
      },
      objectToFB: (WalletSnapshotEntity object, fb.Builder fbb) {
        final snapshotKeyOffset = fbb.writeString(object.snapshotKey);
        final activePlanLabelOffset = fbb.writeString(object.activePlanLabel);
        final historyJsonOffset = fbb.writeString(object.historyJson);
        fbb.startTable(7);
        fbb.addInt64(0, object.dbId);
        fbb.addOffset(1, snapshotKeyOffset);
        fbb.addInt64(2, object.balance);
        fbb.addOffset(3, activePlanLabelOffset);
        fbb.addOffset(4, historyJsonOffset);
        fbb.addInt64(5, object.updatedAtEpochMs);
        fbb.finish(fbb.endTable());
        return object.dbId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dbIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final snapshotKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final balanceParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final activePlanLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final historyJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final updatedAtEpochMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = WalletSnapshotEntity(
          dbId: dbIdParam,
          snapshotKey: snapshotKeyParam,
          balance: balanceParam,
          activePlanLabel: activePlanLabelParam,
          historyJson: historyJsonParam,
          updatedAtEpochMs: updatedAtEpochMsParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AiConversationEntity] entity fields to define ObjectBox queries.
class AiConversationEntity_ {
  /// See [AiConversationEntity.dbId].
  static final dbId = obx.QueryIntegerProperty<AiConversationEntity>(
    _entities[0].properties[0],
  );

  /// See [AiConversationEntity.conversationId].
  static final conversationId = obx.QueryStringProperty<AiConversationEntity>(
    _entities[0].properties[1],
  );

  /// See [AiConversationEntity.profileId].
  static final profileId = obx.QueryStringProperty<AiConversationEntity>(
    _entities[0].properties[2],
  );

  /// See [AiConversationEntity.scope].
  static final scope = obx.QueryStringProperty<AiConversationEntity>(
    _entities[0].properties[3],
  );

  /// See [AiConversationEntity.messagesJson].
  static final messagesJson = obx.QueryStringProperty<AiConversationEntity>(
    _entities[0].properties[4],
  );

  /// See [AiConversationEntity.updatedAtEpochMs].
  static final updatedAtEpochMs =
      obx.QueryIntegerProperty<AiConversationEntity>(
        _entities[0].properties[5],
      );
}

/// [BirthProfileEntity] entity fields to define ObjectBox queries.
class BirthProfileEntity_ {
  /// See [BirthProfileEntity.dbId].
  static final dbId = obx.QueryIntegerProperty<BirthProfileEntity>(
    _entities[1].properties[0],
  );

  /// See [BirthProfileEntity.profileId].
  static final profileId = obx.QueryStringProperty<BirthProfileEntity>(
    _entities[1].properties[1],
  );

  /// See [BirthProfileEntity.name].
  static final name = obx.QueryStringProperty<BirthProfileEntity>(
    _entities[1].properties[2],
  );

  /// See [BirthProfileEntity.gender].
  static final gender = obx.QueryStringProperty<BirthProfileEntity>(
    _entities[1].properties[3],
  );

  /// See [BirthProfileEntity.calendarType].
  static final calendarType = obx.QueryStringProperty<BirthProfileEntity>(
    _entities[1].properties[4],
  );

  /// See [BirthProfileEntity.birthDateEpochMs].
  static final birthDateEpochMs = obx.QueryIntegerProperty<BirthProfileEntity>(
    _entities[1].properties[5],
  );

  /// See [BirthProfileEntity.birthHourLabel].
  static final birthHourLabel = obx.QueryStringProperty<BirthProfileEntity>(
    _entities[1].properties[6],
  );

  /// See [BirthProfileEntity.birthMinute].
  static final birthMinute = obx.QueryIntegerProperty<BirthProfileEntity>(
    _entities[1].properties[7],
  );

  /// See [BirthProfileEntity.birthPlace].
  static final birthPlace = obx.QueryStringProperty<BirthProfileEntity>(
    _entities[1].properties[8],
  );

  /// See [BirthProfileEntity.timezone].
  static final timezone = obx.QueryStringProperty<BirthProfileEntity>(
    _entities[1].properties[9],
  );

  /// See [BirthProfileEntity.birthTimeConfidence].
  static final birthTimeConfidence =
      obx.QueryStringProperty<BirthProfileEntity>(_entities[1].properties[10]);

  /// See [BirthProfileEntity.mainFocusJson].
  static final mainFocusJson = obx.QueryStringProperty<BirthProfileEntity>(
    _entities[1].properties[11],
  );

  /// See [BirthProfileEntity.isMain].
  static final isMain = obx.QueryBooleanProperty<BirthProfileEntity>(
    _entities[1].properties[12],
  );
}

/// [ChartCacheEntity] entity fields to define ObjectBox queries.
class ChartCacheEntity_ {
  /// See [ChartCacheEntity.dbId].
  static final dbId = obx.QueryIntegerProperty<ChartCacheEntity>(
    _entities[2].properties[0],
  );

  /// See [ChartCacheEntity.cacheKey].
  static final cacheKey = obx.QueryStringProperty<ChartCacheEntity>(
    _entities[2].properties[1],
  );

  /// See [ChartCacheEntity.profileId].
  static final profileId = obx.QueryStringProperty<ChartCacheEntity>(
    _entities[2].properties[2],
  );

  /// See [ChartCacheEntity.year].
  static final year = obx.QueryIntegerProperty<ChartCacheEntity>(
    _entities[2].properties[3],
  );

  /// See [ChartCacheEntity.engineVersion].
  static final engineVersion = obx.QueryStringProperty<ChartCacheEntity>(
    _entities[2].properties[4],
  );

  /// See [ChartCacheEntity.schemaVersion].
  static final schemaVersion = obx.QueryStringProperty<ChartCacheEntity>(
    _entities[2].properties[5],
  );

  /// See [ChartCacheEntity.snapshotHash].
  static final snapshotHash = obx.QueryStringProperty<ChartCacheEntity>(
    _entities[2].properties[6],
  );

  /// See [ChartCacheEntity.snapshotJson].
  static final snapshotJson = obx.QueryStringProperty<ChartCacheEntity>(
    _entities[2].properties[7],
  );

  /// See [ChartCacheEntity.summaryJson].
  static final summaryJson = obx.QueryStringProperty<ChartCacheEntity>(
    _entities[2].properties[8],
  );

  /// See [ChartCacheEntity.updatedAtEpochMs].
  static final updatedAtEpochMs = obx.QueryIntegerProperty<ChartCacheEntity>(
    _entities[2].properties[9],
  );
}

/// [JournalEntryEntity] entity fields to define ObjectBox queries.
class JournalEntryEntity_ {
  /// See [JournalEntryEntity.dbId].
  static final dbId = obx.QueryIntegerProperty<JournalEntryEntity>(
    _entities[3].properties[0],
  );

  /// See [JournalEntryEntity.entryId].
  static final entryId = obx.QueryStringProperty<JournalEntryEntity>(
    _entities[3].properties[1],
  );

  /// See [JournalEntryEntity.profileId].
  static final profileId = obx.QueryStringProperty<JournalEntryEntity>(
    _entities[3].properties[2],
  );

  /// See [JournalEntryEntity.createdAtLabel].
  static final createdAtLabel = obx.QueryStringProperty<JournalEntryEntity>(
    _entities[3].properties[3],
  );

  /// See [JournalEntryEntity.createdAtEpochMs].
  static final createdAtEpochMs = obx.QueryIntegerProperty<JournalEntryEntity>(
    _entities[3].properties[4],
  );

  /// See [JournalEntryEntity.mood].
  static final mood = obx.QueryStringProperty<JournalEntryEntity>(
    _entities[3].properties[5],
  );

  /// See [JournalEntryEntity.title].
  static final title = obx.QueryStringProperty<JournalEntryEntity>(
    _entities[3].properties[6],
  );

  /// See [JournalEntryEntity.body].
  static final body = obx.QueryStringProperty<JournalEntryEntity>(
    _entities[3].properties[7],
  );

  /// See [JournalEntryEntity.sentimentLabel].
  static final sentimentLabel = obx.QueryStringProperty<JournalEntryEntity>(
    _entities[3].properties[8],
  );
}

/// [PendingSyncOperationEntity] entity fields to define ObjectBox queries.
class PendingSyncOperationEntity_ {
  /// See [PendingSyncOperationEntity.dbId].
  static final dbId = obx.QueryIntegerProperty<PendingSyncOperationEntity>(
    _entities[4].properties[0],
  );

  /// See [PendingSyncOperationEntity.operationId].
  static final operationId =
      obx.QueryStringProperty<PendingSyncOperationEntity>(
        _entities[4].properties[1],
      );

  /// See [PendingSyncOperationEntity.entityType].
  static final entityType = obx.QueryStringProperty<PendingSyncOperationEntity>(
    _entities[4].properties[2],
  );

  /// See [PendingSyncOperationEntity.operationType].
  static final operationType =
      obx.QueryStringProperty<PendingSyncOperationEntity>(
        _entities[4].properties[3],
      );

  /// See [PendingSyncOperationEntity.payloadJson].
  static final payloadJson =
      obx.QueryStringProperty<PendingSyncOperationEntity>(
        _entities[4].properties[4],
      );

  /// See [PendingSyncOperationEntity.createdAtEpochMs].
  static final createdAtEpochMs =
      obx.QueryIntegerProperty<PendingSyncOperationEntity>(
        _entities[4].properties[5],
      );

  /// See [PendingSyncOperationEntity.lastAttemptAtEpochMs].
  static final lastAttemptAtEpochMs =
      obx.QueryIntegerProperty<PendingSyncOperationEntity>(
        _entities[4].properties[6],
      );

  /// See [PendingSyncOperationEntity.attemptCount].
  static final attemptCount =
      obx.QueryIntegerProperty<PendingSyncOperationEntity>(
        _entities[4].properties[7],
      );
}

/// [UnlockContentEntity] entity fields to define ObjectBox queries.
class UnlockContentEntity_ {
  /// See [UnlockContentEntity.dbId].
  static final dbId = obx.QueryIntegerProperty<UnlockContentEntity>(
    _entities[5].properties[0],
  );

  /// See [UnlockContentEntity.unlockKey].
  static final unlockKey = obx.QueryStringProperty<UnlockContentEntity>(
    _entities[5].properties[1],
  );

  /// See [UnlockContentEntity.profileId].
  static final profileId = obx.QueryStringProperty<UnlockContentEntity>(
    _entities[5].properties[2],
  );

  /// See [UnlockContentEntity.contentType].
  static final contentType = obx.QueryStringProperty<UnlockContentEntity>(
    _entities[5].properties[3],
  );

  /// See [UnlockContentEntity.contentKey].
  static final contentKey = obx.QueryStringProperty<UnlockContentEntity>(
    _entities[5].properties[4],
  );

  /// See [UnlockContentEntity.unlockMethod].
  static final unlockMethod = obx.QueryStringProperty<UnlockContentEntity>(
    _entities[5].properties[5],
  );

  /// See [UnlockContentEntity.coinSpent].
  static final coinSpent = obx.QueryIntegerProperty<UnlockContentEntity>(
    _entities[5].properties[6],
  );

  /// See [UnlockContentEntity.createdAtEpochMs].
  static final createdAtEpochMs = obx.QueryIntegerProperty<UnlockContentEntity>(
    _entities[5].properties[7],
  );
}

/// [WalletLedgerEntity] entity fields to define ObjectBox queries.
class WalletLedgerEntity_ {
  /// See [WalletLedgerEntity.dbId].
  static final dbId = obx.QueryIntegerProperty<WalletLedgerEntity>(
    _entities[6].properties[0],
  );

  /// See [WalletLedgerEntity.entryId].
  static final entryId = obx.QueryStringProperty<WalletLedgerEntity>(
    _entities[6].properties[1],
  );

  /// See [WalletLedgerEntity.title].
  static final title = obx.QueryStringProperty<WalletLedgerEntity>(
    _entities[6].properties[2],
  );

  /// See [WalletLedgerEntity.amount].
  static final amount = obx.QueryIntegerProperty<WalletLedgerEntity>(
    _entities[6].properties[3],
  );

  /// See [WalletLedgerEntity.createdAtLabel].
  static final createdAtLabel = obx.QueryStringProperty<WalletLedgerEntity>(
    _entities[6].properties[4],
  );

  /// See [WalletLedgerEntity.createdAtEpochMs].
  static final createdAtEpochMs = obx.QueryIntegerProperty<WalletLedgerEntity>(
    _entities[6].properties[5],
  );

  /// See [WalletLedgerEntity.source].
  static final source = obx.QueryStringProperty<WalletLedgerEntity>(
    _entities[6].properties[6],
  );
}

/// [WalletSnapshotEntity] entity fields to define ObjectBox queries.
class WalletSnapshotEntity_ {
  /// See [WalletSnapshotEntity.dbId].
  static final dbId = obx.QueryIntegerProperty<WalletSnapshotEntity>(
    _entities[7].properties[0],
  );

  /// See [WalletSnapshotEntity.snapshotKey].
  static final snapshotKey = obx.QueryStringProperty<WalletSnapshotEntity>(
    _entities[7].properties[1],
  );

  /// See [WalletSnapshotEntity.balance].
  static final balance = obx.QueryIntegerProperty<WalletSnapshotEntity>(
    _entities[7].properties[2],
  );

  /// See [WalletSnapshotEntity.activePlanLabel].
  static final activePlanLabel = obx.QueryStringProperty<WalletSnapshotEntity>(
    _entities[7].properties[3],
  );

  /// See [WalletSnapshotEntity.historyJson].
  static final historyJson = obx.QueryStringProperty<WalletSnapshotEntity>(
    _entities[7].properties[4],
  );

  /// See [WalletSnapshotEntity.updatedAtEpochMs].
  static final updatedAtEpochMs =
      obx.QueryIntegerProperty<WalletSnapshotEntity>(
        _entities[7].properties[5],
      );
}
